[package]
name = "support"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
sonic-rs.workspace = true
twilight-http.workspace = true
twilight-model.workspace = true
wit-bindgen.workspace = true
wstd.workspace = true

[lib]
crate-type = ["cdylib"]
