[package]
name = "extension-requests"
version = "0.4.0"
edition = "2024"

[dependencies]
serde.workspace = true
sonic-rs.workspace = true
twilight-http.workspace = true
twilight-model.workspace = true
wit-bindgen.workspace = true

url = "2"

[lib]
crate-type = ["cdylib"]
